# Generated by Django 2.2.4 on 2020-06-17 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200616_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(default='AAABBBCCC23', max_length=8, validators=[django.core.validators.MinLengthValidator(8)]),
            preserve_default=False,
        ),
    ]
