# Generated by Django 2.2.4 on 2020-06-17 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200617_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quantity',
            new_name='stock_quantity',
        ),
    ]
