# Generated by Django 2.2.4 on 2020-06-18 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_imageuploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='upc',
            field=models.IntegerField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
    ]
