# Generated by Django 2.2.4 on 2020-06-18 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_item_upc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='upc',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(12)]),
        ),
    ]
