# Generated by Django 2.2.4 on 2020-06-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200618_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
