# Generated by Django 2.2.4 on 2020-06-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200620_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='refused',
        ),
        migrations.AddField(
            model_name='order',
            name='refund_refused',
            field=models.BooleanField(default=False),
        ),
    ]
