# Generated by Django 2.2.4 on 2020-06-22 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_refund_granted'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='itemPrice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemPrice', to='core.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('DR', 'Drink'), ('DO', 'Deals & Offers'), ('DI', 'Dairy Items'), ('FV', 'Fruits & Vegetables'), ('GR', 'Groceries'), ('HS', 'Household Supplies'), ('BP', 'Beauty & Personal Care'), ('OT', 'Others')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
