# Generated by Django 2.2.4 on 2020-06-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200622_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='itemPrice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
