# Generated by Django 2.2.4 on 2020-06-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200622_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='itemPriceP',
        ),
    ]
