# Generated by Django 2.2.4 on 2020-06-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_orderitem_itempricep'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='purchase',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
