# Generated by Django 2.2.4 on 2020-06-23 08:24

import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_itemprice_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrdered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('upc', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(12)])),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('DR', 'Drink'), ('DO', 'Deals & Offers'), ('DI', 'Dairy Items'), ('FV', 'Fruits & Vegetables'), ('GR', 'Groceries'), ('HS', 'Household Supplies'), ('BP', 'Beauty & Personal Care'), ('OT', 'Others')], max_length=2)),
                ('label', models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=1)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.upload_location)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.OrderItem')),
            ],
        ),
        migrations.DeleteModel(
            name='ItemPrice',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ordered_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ItemOrdered'),
        ),
    ]
