# Generated by Django 2.2.4 on 2020-06-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200623_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemordered',
            name='item',
        ),
    ]
