# Generated by Django 2.2.4 on 2020-06-23 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200623_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='ordered_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ItemOrdered'),
        ),
    ]
