# Generated by Django 2.2.4 on 2020-06-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200623_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemordered',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='itemordered',
            name='upc',
        ),
    ]
